// Code generated by cmd/main. DO NOT EDIT.
package model_test

import (
	"testing"
	"time"

	"github.com/flussonic/go-flussonic/vision-identification/model"
	"github.com/stretchr/testify/assert"
)

func TestCollectionResponse(t *testing.T) {
	t.Run("EstimatedCountValue", func(t *testing.T) {
		obj := model.NewCollectionResponse()
		value := 42
		obj.SetEstimatedCount(value)
		assert.NotNil(t, obj.EstimatedCount())
		assert.Equal(t, value, *obj.EstimatedCount())
	})

	t.Run("NextValue", func(t *testing.T) {
		obj := model.NewCollectionResponse()
		value := "test"
		obj.SetNext(value)
		assert.NotNil(t, obj.Next())
		assert.Equal(t, value, *obj.Next())
	})

	t.Run("PrevValue", func(t *testing.T) {
		obj := model.NewCollectionResponse()
		value := "test"
		obj.SetPrev(value)
		assert.NotNil(t, obj.Prev())
		assert.Equal(t, value, *obj.Prev())
	})
}

func TestEpisodeFingerprint(t *testing.T) {
	t.Run("EpisodeIDValue", func(t *testing.T) {
		obj := model.NewEpisodeFingerprint()
		value := 42
		obj.SetEpisodeID(value)
		assert.NotNil(t, obj.EpisodeID())
		assert.Equal(t, value, *obj.EpisodeID())
	})

	t.Run("FingerprintValue", func(t *testing.T) {
		obj := model.NewEpisodeFingerprint()
		value := model.NewVisionFaceFingerprint()
		value.SetData(model.Base64("test"))
		value.SetVersion("test")
		obj.SetFingerprint(value)
		result := obj.Fingerprint()
		assert.NotNil(t, result)
		assert.Equal(t, model.Base64("test"), result.Data())
		assert.Equal(t, "test", result.Version())
	})
}

func TestEpisodeIdentificationError(t *testing.T) {
	t.Run("CodeValue", func(t *testing.T) {
		obj := model.NewEpisodeIdentificationError()
		value := model.EpisodeIdentificationErrorCode("test")
		obj.SetCode(value)
		assert.NotNil(t, obj.Code())
		assert.Equal(t, value, *obj.Code())
	})
}

func TestEpisodeIdentificationRequest(t *testing.T) {
	t.Run("EpisodesValue", func(t *testing.T) {
		obj := model.NewEpisodeIdentificationRequest()
		item1 := model.NewEpisodeFingerprint()
		item2 := model.NewEpisodeFingerprint()
		item1.SetEpisodeID(1)
		item2.SetEpisodeID(2)
		value := []model.EpisodeFingerprint{item1, item2}
		obj.SetEpisodes(value)
		result := obj.Episodes()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.NotNil(t, result[0].EpisodeID())
			assert.Equal(t, 1, *result[0].EpisodeID())
		}
	})
}

func TestError(t *testing.T) {
	t.Run("CodeValue", func(t *testing.T) {
		obj := model.NewError()
		value := "test"
		obj.SetCode(value)
		assert.NotNil(t, obj.Code())
		assert.Equal(t, value, *obj.Code())
	})

	t.Run("IDValue", func(t *testing.T) {
		obj := model.NewError()
		value := "test"
		obj.SetID(value)
		assert.NotNil(t, obj.ID())
		assert.Equal(t, value, *obj.ID())
	})

	t.Run("SourceValue", func(t *testing.T) {
		obj := model.NewError()
		value := model.NewErrorSource()
		value.SetParameter("test")
		value.SetPointer("test")
		obj.SetSource(value)
		result := obj.Source()
		assert.NotNil(t, result)
		assert.NotNil(t, result.Parameter())
		assert.Equal(t, "test", *result.Parameter())
		assert.NotNil(t, result.Pointer())
		assert.Equal(t, "test", *result.Pointer())
	})

	t.Run("StatusValue", func(t *testing.T) {
		obj := model.NewError()
		value := "test"
		obj.SetStatus(value)
		assert.NotNil(t, obj.Status())
		assert.Equal(t, value, *obj.Status())
	})

	t.Run("TitleValue", func(t *testing.T) {
		obj := model.NewError()
		value := "test"
		obj.SetTitle(value)
		assert.NotNil(t, obj.Title())
		assert.Equal(t, value, *obj.Title())
	})
}

func TestErrorResponse(t *testing.T) {
	t.Run("ErrorsValue", func(t *testing.T) {
		obj := model.NewErrorResponse()
		item1 := model.NewError()
		item2 := model.NewError()
		item1.SetCode("item1")
		item2.SetCode("item2")
		item1.SetID("item1")
		item2.SetID("item2")
		value := []model.Error{item1, item2}
		obj.SetErrors(value)
		result := obj.Errors()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.NotNil(t, result[0].Code())
			assert.Equal(t, "item1", *result[0].Code())
			assert.NotNil(t, result[0].ID())
			assert.Equal(t, "item1", *result[0].ID())
		}
	})
}

func TestErrorSource(t *testing.T) {
	t.Run("ParameterValue", func(t *testing.T) {
		obj := model.NewErrorSource()
		value := "test"
		obj.SetParameter(value)
		assert.NotNil(t, obj.Parameter())
		assert.Equal(t, value, *obj.Parameter())
	})

	t.Run("PointerValue", func(t *testing.T) {
		obj := model.NewErrorSource()
		value := "test"
		obj.SetPointer(value)
		assert.NotNil(t, obj.Pointer())
		assert.Equal(t, value, *obj.Pointer())
	})
}

func TestIdentificationMetrics(t *testing.T) {
	t.Run("EpisodesIdentifiedCountValue", func(t *testing.T) {
		obj := model.NewIdentificationMetrics()
		value := 42
		obj.SetEpisodesIdentifiedCount(value)
		assert.NotNil(t, obj.EpisodesIdentifiedCount())
		assert.Equal(t, value, *obj.EpisodesIdentifiedCount())
	})

	t.Run("EpisodesInputCountValue", func(t *testing.T) {
		obj := model.NewIdentificationMetrics()
		value := 42
		obj.SetEpisodesInputCount(value)
		assert.NotNil(t, obj.EpisodesInputCount())
		assert.Equal(t, value, *obj.EpisodesInputCount())
	})

	t.Run("EpisodesProcessingTimeValue", func(t *testing.T) {
		obj := model.NewIdentificationMetrics()
		value := model.Milliseconds(42)
		obj.SetEpisodesProcessingTime(value)
		assert.NotNil(t, obj.EpisodesProcessingTime())
		assert.Equal(t, value, *obj.EpisodesProcessingTime())
	})

	t.Run("PersonsCreatedCountValue", func(t *testing.T) {
		obj := model.NewIdentificationMetrics()
		value := 42
		obj.SetPersonsCreatedCount(value)
		assert.NotNil(t, obj.PersonsCreatedCount())
		assert.Equal(t, value, *obj.PersonsCreatedCount())
	})
}

func TestIdentifiedEpisodeIdentificationError(t *testing.T) {
	t.Run("CodeValue", func(t *testing.T) {
		obj := model.NewIdentifiedEpisodeIdentificationError()
		value := model.EpisodeIdentificationErrorCode("test")
		obj.SetCode(value)
		assert.NotNil(t, obj.Code())
		assert.Equal(t, value, *obj.Code())
	})
}

func TestIdentifiedEpisode(t *testing.T) {
	t.Run("EpisodeIDValue", func(t *testing.T) {
		obj := model.NewIdentifiedEpisode()
		value := 42
		obj.SetEpisodeID(value)
		assert.NotNil(t, obj.EpisodeID())
		assert.Equal(t, value, *obj.EpisodeID())
	})

	t.Run("IdentificationErrorValue", func(t *testing.T) {
		obj := model.NewIdentifiedEpisode()
		value := model.NewIdentifiedEpisodeIdentificationError()
		value.SetCode(model.EpisodeIdentificationErrorCode("test"))
		obj.SetIdentificationError(value)
		result := obj.IdentificationError()
		assert.NotNil(t, result)
		assert.NotNil(t, result.Code())
		assert.Equal(t, model.EpisodeIdentificationErrorCode("test"), *result.Code())
	})

	t.Run("MatchedPersonsValue", func(t *testing.T) {
		obj := model.NewIdentifiedEpisode()
		item1 := model.NewVisionPersonMatch()
		item2 := model.NewVisionPersonMatch()
		item1.SetMatchScore(3.14)
		item2.SetMatchScore(3.14)
		value := []model.VisionPersonMatch{item1, item2}
		obj.SetMatchedPersons(value)
		result := obj.MatchedPersons()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.Equal(t, 3.14, result[0].MatchScore())
		}
	})
}

func TestIdentifiedEpisodesList(t *testing.T) {
	t.Run("EpisodesValue", func(t *testing.T) {
		obj := model.NewIdentifiedEpisodesList()
		item1 := model.NewIdentifiedEpisode()
		item2 := model.NewIdentifiedEpisode()
		item1.SetEpisodeID(1)
		item2.SetEpisodeID(2)
		value := []model.IdentifiedEpisode{item1, item2}
		obj.SetEpisodes(value)
		result := obj.Episodes()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.NotNil(t, result[0].EpisodeID())
			assert.Equal(t, 1, *result[0].EpisodeID())
		}
	})
}

func TestVisionFaceFingerprint(t *testing.T) {
	t.Run("DataValue", func(t *testing.T) {
		obj := model.NewVisionFaceFingerprint()
		value := model.Base64("test")
		obj.SetData(value)
		assert.Equal(t, value, obj.Data())
	})

	t.Run("VersionValue", func(t *testing.T) {
		obj := model.NewVisionFaceFingerprint()
		value := "test"
		obj.SetVersion(value)
		assert.Equal(t, value, obj.Version())
	})
}

func TestVisionPerson(t *testing.T) {
	t.Run("DeletedAtValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		tNow := time.Now().UnixMilli()
		obj.SetDeletedAt(model.UtcMs(float64(tNow)))
		assert.NotNil(t, obj.DeletedAt())
		assert.Equal(t, model.UtcMs(float64(tNow)), *obj.DeletedAt())
	})

	t.Run("ExternalIDValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		value := "test"
		obj.SetExternalID(value)
		assert.NotNil(t, obj.ExternalID())
		assert.Equal(t, value, *obj.ExternalID())
	})

	t.Run("FingerprintsValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		item1 := model.NewVisionFaceFingerprint()
		item2 := model.NewVisionFaceFingerprint()
		item1.SetData(model.Base64("test"))
		item2.SetData(model.Base64("test"))
		item1.SetVersion("item1")
		item2.SetVersion("item2")
		value := []model.VisionFaceFingerprint{item1, item2}
		obj.SetFingerprints(value)
		result := obj.Fingerprints()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.Equal(t, model.Base64("test"), result[0].Data())
			assert.Equal(t, "item1", result[0].Version())
		}
	})

	t.Run("OriginatorValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		value := model.VisionPersonOriginator("test")
		obj.SetOriginator(value)
		assert.Equal(t, value, obj.Originator())
	})

	t.Run("PersonIDValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		value := model.SnowflakeID(42)
		obj.SetPersonID(value)
		assert.Equal(t, value, obj.PersonID())
	})

	t.Run("UpdatedAtValue", func(t *testing.T) {
		obj := model.NewVisionPerson()
		tNow := time.Now().UnixMilli()
		obj.SetUpdatedAt(model.UtcMs(float64(tNow)))
		assert.Equal(t, model.UtcMs(float64(tNow)), obj.UpdatedAt())
	})
}

func TestVisionPersonMatch(t *testing.T) {
	t.Run("MatchScoreValue", func(t *testing.T) {
		obj := model.NewVisionPersonMatch()
		value := 3.14
		obj.SetMatchScore(value)
		assert.Equal(t, value, obj.MatchScore())
	})

	t.Run("PersonValue", func(t *testing.T) {
		obj := model.NewVisionPersonMatch()
		value := model.NewVisionPerson()
		tNow0 := time.Now().UnixMilli()
		value.SetDeletedAt(model.UtcMs(float64(tNow0)))
		value.SetExternalID("test")
		obj.SetPerson(value)
		result := obj.Person()
		assert.NotNil(t, result)
		assert.NotNil(t, result.DeletedAt())
		assert.Equal(t, model.UtcMs(float64(tNow0)), *result.DeletedAt())
		assert.NotNil(t, result.ExternalID())
		assert.Equal(t, "test", *result.ExternalID())
	})
}

func TestVisionPersonMatches(t *testing.T) {
	t.Run("MatchedPersonsValue", func(t *testing.T) {
		obj := model.NewVisionPersonMatches()
		item1 := model.NewVisionPersonMatch()
		item2 := model.NewVisionPersonMatch()
		item1.SetMatchScore(3.14)
		item2.SetMatchScore(3.14)
		value := []model.VisionPersonMatch{item1, item2}
		obj.SetMatchedPersons(value)
		result := obj.MatchedPersons()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.Equal(t, 3.14, result[0].MatchScore())
		}
	})
}

func TestVisionPersonsList(t *testing.T) {
	t.Run("EstimatedCountValue", func(t *testing.T) {
		obj := model.NewVisionPersonsList()
		value := 42
		obj.SetEstimatedCount(value)
		assert.NotNil(t, obj.EstimatedCount())
		assert.Equal(t, value, *obj.EstimatedCount())
	})

	t.Run("NextValue", func(t *testing.T) {
		obj := model.NewVisionPersonsList()
		value := "test"
		obj.SetNext(value)
		assert.NotNil(t, obj.Next())
		assert.Equal(t, value, *obj.Next())
	})

	t.Run("PersonsValue", func(t *testing.T) {
		obj := model.NewVisionPersonsList()
		item1 := model.NewVisionPerson()
		item2 := model.NewVisionPerson()
		tNow1_0 := time.Now().UnixMilli()
		tNow2_0 := time.Now().UnixMilli() + 1000
		item1.SetDeletedAt(model.UtcMs(float64(tNow1_0)))
		item2.SetDeletedAt(model.UtcMs(float64(tNow2_0)))
		item1.SetExternalID("item1")
		item2.SetExternalID("item2")
		value := []model.VisionPerson{item1, item2}
		obj.SetPersons(value)
		result := obj.Persons()
		assert.NotNil(t, result)
		assert.Len(t, result, 2)
		if len(result) > 0 {
			assert.NotNil(t, result[0].DeletedAt())
			assert.Equal(t, model.UtcMs(float64(tNow1_0)), *result[0].DeletedAt())
			assert.NotNil(t, result[0].ExternalID())
			assert.Equal(t, "item1", *result[0].ExternalID())
		}
	})

	t.Run("PrevValue", func(t *testing.T) {
		obj := model.NewVisionPersonsList()
		value := "test"
		obj.SetPrev(value)
		assert.NotNil(t, obj.Prev())
		assert.Equal(t, value, *obj.Prev())
	})
}

func TestVisionServerInfo(t *testing.T) {
	t.Run("BuildValue", func(t *testing.T) {
		obj := model.NewVisionServerInfo()
		value := 42
		obj.SetBuild(value)
		assert.NotNil(t, obj.Build())
		assert.Equal(t, value, *obj.Build())
	})

	t.Run("NowValue", func(t *testing.T) {
		obj := model.NewVisionServerInfo()
		tNow := time.Now().UnixMilli()
		obj.SetNow(model.UtcMs(float64(tNow)))
		assert.NotNil(t, obj.Now())
		assert.Equal(t, model.UtcMs(float64(tNow)), *obj.Now())
	})

	t.Run("SchemaVersionValue", func(t *testing.T) {
		obj := model.NewVisionServerInfo()
		value := "test"
		obj.SetSchemaVersion(value)
		assert.NotNil(t, obj.SchemaVersion())
		assert.Equal(t, value, *obj.SchemaVersion())
	})

	t.Run("ServerVersionValue", func(t *testing.T) {
		obj := model.NewVisionServerInfo()
		value := model.ServerVersion("test")
		obj.SetServerVersion(value)
		assert.NotNil(t, obj.ServerVersion())
		assert.Equal(t, value, *obj.ServerVersion())
	})

	t.Run("StartedAtValue", func(t *testing.T) {
		obj := model.NewVisionServerInfo()
		value := model.Utc(42)
		obj.SetStartedAt(value)
		assert.NotNil(t, obj.StartedAt())
		assert.Equal(t, value, *obj.StartedAt())
	})
}
