// Code generated by cmd/main. DO NOT EDIT.
package model

// base64
type Base64 string

type EpisodeIdentificationErrorCode string

const (
	// It is hard to tell if the person in this episode is someone the system already knows
	// or if it is new and need to be remembered by the system.
	//
	EpisodeIdentificationErrorCodeUncertainMatch EpisodeIdentificationErrorCode = "uncertain_match"
	// There is a person in this episode that the system has not seen before.
	// However, the system can not remember it automatically because the fingerprint or image
	// is not good enough for the system to use for further identifications.
	//
	EpisodeIdentificationErrorCodeBadQuality EpisodeIdentificationErrorCode = "bad_quality"
)

// milliseconds
type Milliseconds int

// server_version
type ServerVersion string

// snowflake_id
type SnowflakeID int

// Unix timestamp in seconds
type Utc int

// Unix timestamp in milliseconds
type UtcMs int

type VisionPersonOriginator string

const (
	// Person is created by operator or external system via API.
	// For example, when you add the person in Watcher UI, it has `originator=api`.
	// But when you edit an automatically created person in UI, `originator=identification_service` remains.
	//
	VisionPersonOriginatorAPI VisionPersonOriginator = "api"
	// Person is created automatically by the Identification service
	// because no matching person was found in the persons database.
	//
	// The Identification service stores unrecognized persons and matches new episodes with them
	// in case if it becomes known who this is (i.e. if operator edits such person in UI to specify name).
	//
	VisionPersonOriginatorIdentificationService VisionPersonOriginator = "identification_service"
)

type CollectionResponse interface {
	// Estimated total number of records for the query (regardless of the cursors).
	// Example: 5
	EstimatedCount() *int
	// Estimated total number of records for the query (regardless of the cursors).
	// Example: 5
	SetEstimatedCount(int) CollectionResponse
	// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fZ3Q9MA==
	Next() *string
	// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fZ3Q9MA==
	SetNext(string) CollectionResponse
	// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
	Prev() *string
	// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
	SetPrev(string) CollectionResponse
	// An object with a list of different timings measured during this API call.
	Timing() any
	// An object with a list of different timings measured during this API call.
	SetTiming(any) CollectionResponse
}

// Fingerprint data with identifier of the episode that contains this fingerprint
// Required: fingerprint
type EpisodeFingerprint interface {
	// Identifier of the episode that contains fingerprint to be identified
	EpisodeID() *int
	// Identifier of the episode that contains fingerprint to be identified
	SetEpisodeID(int) EpisodeFingerprint
	// Fingerprint to be identified
	Fingerprint() VisionFaceFingerprint
	// Fingerprint to be identified
	SetFingerprint(VisionFaceFingerprint) EpisodeFingerprint
}

type EpisodeIdentificationError interface {
	Code() *EpisodeIdentificationErrorCode
	SetCode(EpisodeIdentificationErrorCode) EpisodeIdentificationError
}

// Episodes identification request
type EpisodeIdentificationRequest interface {
	// Batch of episodes containing fingerprints to be identified
	Episodes() []EpisodeFingerprint
	// Batch of episodes containing fingerprints to be identified
	SetEpisodes([]EpisodeFingerprint) EpisodeIdentificationRequest
}

type Error interface {
	// an application-specific error code, expressed as a string value
	Code() *string
	// an application-specific error code, expressed as a string value
	SetCode(string) Error
	// a unique identifier for this particular occurrence of the problem
	ID() *string
	// a unique identifier for this particular occurrence of the problem
	SetID(string) Error
	// a meta object containing non-standard meta-information about the error.
	Meta() map[string]string
	// a meta object containing non-standard meta-information about the error.
	SetMeta(map[string]string) Error
	// an object containing references to the source of the error
	Source() ErrorSource
	// an object containing references to the source of the error
	SetSource(ErrorSource) Error
	// the HTTP status code applicable to this problem, expressed as a string value
	Status() *string
	// the HTTP status code applicable to this problem, expressed as a string value
	SetStatus(string) Error
	// a short, human-readable summary of the problem that SHOULD NOT change from
	// occurrence to occurrence of the problem, except for purposes of localization
	Title() *string
	// a short, human-readable summary of the problem that SHOULD NOT change from
	// occurrence to occurrence of the problem, except for purposes of localization
	SetTitle(string) Error
}

type ErrorResponse interface {
	// List of structured errors
	Errors() []Error
	// List of structured errors
	SetErrors([]Error) ErrorResponse
}

// an object containing references to the source of the error
type ErrorSource interface {
	// a string indicating which URI query parameter caused the error.
	Parameter() *string
	// a string indicating which URI query parameter caused the error.
	SetParameter(string) ErrorSource
	// a JSON Pointer [RFC6901] to the associated entity in the request document
	// [e.g. `"/data"` for a primary data object, or `"/data/attributes/title"` for a specific attribute].
	Pointer() *string
	// a JSON Pointer [RFC6901] to the associated entity in the request document
	// [e.g. `"/data"` for a primary data object, or `"/data/attributes/title"` for a specific attribute].
	SetPointer(string) ErrorSource
}

type IdentificationMetrics interface {
	// The number of identified episodes
	EpisodesIdentifiedCount() *int
	// The number of identified episodes
	SetEpisodesIdentifiedCount(int) IdentificationMetrics
	// The number of received episodes to identificate
	EpisodesInputCount() *int
	// The number of received episodes to identificate
	SetEpisodesInputCount(int) IdentificationMetrics
	// Total time spent on episode identification
	// Format: milliseconds (milliseconds)
	EpisodesProcessingTime() *Milliseconds
	// Total time spent on episode identification
	// Format: milliseconds (milliseconds)
	SetEpisodesProcessingTime(Milliseconds) IdentificationMetrics
	// The number of created persons
	PersonsCreatedCount() *int
	// The number of created persons
	SetPersonsCreatedCount(int) IdentificationMetrics
}

type IdentifiedEpisode interface {
	// Identifier of the episode that contains fingerprint to be identified
	EpisodeID() *int
	// Identifier of the episode that contains fingerprint to be identified
	SetEpisodeID(int) IdentifiedEpisode
	IdentificationError() IdentifiedEpisodeIdentificationError
	SetIdentificationError(IdentifiedEpisodeIdentificationError) IdentifiedEpisode
	// List of matched persons with similarity metric
	MatchedPersons() []VisionPersonMatch
	// List of matched persons with similarity metric
	SetMatchedPersons([]VisionPersonMatch) IdentifiedEpisode
}

type IdentifiedEpisodeIdentificationError interface {
	Code() *EpisodeIdentificationErrorCode
	SetCode(EpisodeIdentificationErrorCode) IdentifiedEpisodeIdentificationError
}

// Batch of identified fingerprints
type IdentifiedEpisodesList interface {
	// Batch of identified fingerprints
	Episodes() []IdentifiedEpisode
	// Batch of identified fingerprints
	SetEpisodes([]IdentifiedEpisode) IdentifiedEpisodesList
}

// Digital fingerprint of the face
// Required: data, version
type VisionFaceFingerprint interface {
	// Base64 encoded representation of the fingerprint
	// Format: base64 (base64)
	Data() Base64
	// Base64 encoded representation of the fingerprint
	// Format: base64 (base64)
	SetData(Base64) VisionFaceFingerprint
	// Version identifier of the fingerprint's data. The version is assigned automatically.
	// Fingerprints of different versions cannot be compared to each other.
	// Examples: aabbccdd, c6ba4246
	Version() string
	// Version identifier of the fingerprint's data. The version is assigned automatically.
	// Fingerprints of different versions cannot be compared to each other.
	// Examples: aabbccdd, c6ba4246
	SetVersion(string) VisionFaceFingerprint
}

// Person
// Required: person_id, updated_at, originator
type VisionPerson interface {
	// When this person was marked as deleted
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.637095014573e+12
	DeletedAt() *UtcMs
	// When this person was marked as deleted
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.637095014573e+12
	SetDeletedAt(UtcMs) VisionPerson
	// Identifier of the person in the external system.
	// Use it when supplying the recognition results further into the external system
	// (e.g. for access level check) if the person identifiers in the external system
	// are different from the ones in Flussonic Identification database.
	// This field may contain `null` when video analytics detects a new person
	// which explicitly has no association in the external system (i.e. if `originator=identification_service`).
	// Examples: dedcc8e8
	ExternalID() *string
	// Identifier of the person in the external system.
	// Use it when supplying the recognition results further into the external system
	// (e.g. for access level check) if the person identifiers in the external system
	// are different from the ones in Flussonic Identification database.
	// This field may contain `null` when video analytics detects a new person
	// which explicitly has no association in the external system (i.e. if `originator=identification_service`).
	// Examples: dedcc8e8
	SetExternalID(string) VisionPerson
	// Digital fingerprints of the person.
	// Videoanalytics makes digital fingerprint of the person
	// using uploaded photos or videostreams being processed
	Fingerprints() []VisionFaceFingerprint
	// Digital fingerprints of the person.
	// Videoanalytics makes digital fingerprint of the person
	// using uploaded photos or videostreams being processed
	SetFingerprints([]VisionFaceFingerprint) VisionPerson
	// Indicates the way this person was created:
	// manually via an api or automatically in the identification service.
	Originator() VisionPersonOriginator
	// Indicates the way this person was created:
	// manually via an api or automatically in the identification service.
	SetOriginator(VisionPersonOriginator) VisionPerson
	// Identifier of the person
	// Format: snowflake_id (snowflake_id)
	// Examples: 7.036001172460667e+18
	PersonID() SnowflakeID
	// Identifier of the person
	// Format: snowflake_id (snowflake_id)
	// Examples: 7.036001172460667e+18
	SetPersonID(SnowflakeID) VisionPerson
	// When this person was last updated
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.637034282845e+12
	UpdatedAt() UtcMs
	// When this person was last updated
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.637034282845e+12
	SetUpdatedAt(UtcMs) VisionPerson
}

// Person matching information
// Required: person, match_score
type VisionPersonMatch interface {
	// Score of the match with person. 1.0 means absolute match
	MatchScore() float64
	// Score of the match with person. 1.0 means absolute match
	SetMatchScore(float64) VisionPersonMatch
	// Matched person
	Person() VisionPerson
	// Matched person
	SetPerson(VisionPerson) VisionPersonMatch
}

// Person matching information
type VisionPersonMatches interface {
	// List of matched persons with similarity metric
	MatchedPersons() []VisionPersonMatch
	// List of matched persons with similarity metric
	SetMatchedPersons([]VisionPersonMatch) VisionPersonMatches
}

type VisionPersonsList interface {
	// Estimated total number of records for the query (regardless of the cursors).
	// Example: 5
	EstimatedCount() *int
	// Estimated total number of records for the query (regardless of the cursors).
	// Example: 5
	SetEstimatedCount(int) VisionPersonsList
	// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fZ3Q9MA==
	Next() *string
	// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fZ3Q9MA==
	SetNext(string) VisionPersonsList
	// List of fetched persons according to the query parameters.
	Persons() []VisionPerson
	// List of fetched persons according to the query parameters.
	SetPersons([]VisionPerson) VisionPersonsList
	// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
	Prev() *string
	// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
	// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
	// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
	SetPrev(string) VisionPersonsList
	// An object with a list of different timings measured during this API call.
	Timing() any
	// An object with a list of different timings measured during this API call.
	SetTiming(any) VisionPersonsList
	// Collection returns the collection items
	Collection() []VisionPerson
}

type VisionServerInfo interface {
	// Build version
	// Example: 235
	Build() *int
	// Build version
	// Example: 235
	SetBuild(int) VisionServerInfo
	// Server's current timestamp
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.639337825e+12
	Now() *UtcMs
	// Server's current timestamp
	// Format: utc_ms (Unix timestamp in milliseconds)
	// Example: 1.639337825e+12
	SetNow(UtcMs) VisionServerInfo
	// API schema revision implemented in this version of the server
	// Example: 5e5e91d8
	SchemaVersion() *string
	// API schema revision implemented in this version of the server
	// Example: 5e5e91d8
	SetSchemaVersion(string) VisionServerInfo
	// Package version of the server. Might be simple a number of release like 21.11 or longer if you have a rolling release installed.
	// Format: server_version (server_version)
	// Example: 21.12
	ServerVersion() *ServerVersion
	// Package version of the server. Might be simple a number of release like 21.11 or longer if you have a rolling release installed.
	// Format: server_version (server_version)
	// Example: 21.12
	SetServerVersion(ServerVersion) VisionServerInfo
	// Timestamp when this instance was started
	// Format: utc (Unix timestamp in seconds)
	// Example: 1.639337825e+09
	StartedAt() *Utc
	// Timestamp when this instance was started
	// Format: utc (Unix timestamp in seconds)
	// Example: 1.639337825e+09
	SetStartedAt(Utc) VisionServerInfo
}

type CollectionResponseImpl struct {
	EstimatedCountValue *int    `json:"estimated_count,omitempty" validate:"omitempty"`
	NextValue           *string `json:"next,omitempty" validate:"omitempty"`
	PrevValue           *string `json:"prev,omitempty" validate:"omitempty"`
	TimingValue         any     `json:"timing,omitempty" validate:"omitempty"`
}

// Fingerprint data with identifier of the episode that contains this fingerprint
// Required: fingerprint
type EpisodeFingerprintImpl struct {
	EpisodeIDValue   *int                       `json:"episode_id,omitempty" validate:"omitempty"`
	FingerprintValue *VisionFaceFingerprintImpl `json:"fingerprint" validate:"required"`
}

type EpisodeIdentificationErrorImpl struct {
	CodeValue *EpisodeIdentificationErrorCode `json:"code,omitempty" validate:"omitempty,oneof=uncertain_match bad_quality"`
}

// Episodes identification request
type EpisodeIdentificationRequestImpl struct {
	EpisodesValue []*EpisodeFingerprintImpl `json:"episodes,omitempty" validate:"omitempty"`
}

type ErrorImpl struct {
	CodeValue   *string           `json:"code,omitempty" validate:"omitempty"`
	IDValue     *string           `json:"id,omitempty" validate:"omitempty"`
	MetaValue   map[string]string `json:"meta,omitempty" validate:"omitempty"`
	SourceValue *ErrorSourceImpl  `json:"source,omitempty" validate:"omitempty"`
	StatusValue *string           `json:"status,omitempty" validate:"omitempty"`
	TitleValue  *string           `json:"title,omitempty" validate:"omitempty"`
}

type ErrorResponseImpl struct {
	ErrorsValue []*ErrorImpl `json:"errors,omitempty" validate:"omitempty"`
}

// an object containing references to the source of the error
type ErrorSourceImpl struct {
	ParameterValue *string `json:"parameter,omitempty" validate:"omitempty"`
	PointerValue   *string `json:"pointer,omitempty" validate:"omitempty"`
}

type IdentificationMetricsImpl struct {
	EpisodesIdentifiedCountValue *int          `json:"episodes_identified_count,omitempty" validate:"omitempty"`
	EpisodesInputCountValue      *int          `json:"episodes_input_count,omitempty" validate:"omitempty"`
	EpisodesProcessingTimeValue  *Milliseconds `json:"episodes_processing_time,omitempty" validate:"omitempty"`
	PersonsCreatedCountValue     *int          `json:"persons_created_count,omitempty" validate:"omitempty"`
}

type IdentifiedEpisodeImpl struct {
	EpisodeIDValue           *int                                      `json:"episode_id,omitempty" validate:"omitempty"`
	IdentificationErrorValue *IdentifiedEpisodeIdentificationErrorImpl `json:"identification_error,omitempty" validate:"omitempty"`
	MatchedPersonsValue      []*VisionPersonMatchImpl                  `json:"matched_persons,omitempty" validate:"omitempty"`
}

type IdentifiedEpisodeIdentificationErrorImpl struct {
	CodeValue *EpisodeIdentificationErrorCode `json:"code,omitempty" validate:"omitempty,oneof=uncertain_match bad_quality"`
}

// Batch of identified fingerprints
type IdentifiedEpisodesListImpl struct {
	EpisodesValue []*IdentifiedEpisodeImpl `json:"episodes,omitempty" validate:"omitempty"`
}

// Digital fingerprint of the face
// Required: data, version
type VisionFaceFingerprintImpl struct {
	DataValue    Base64 `json:"data" validate:"required,base64"`
	VersionValue string `json:"version" validate:"required"`
}

// Person
// Required: person_id, updated_at, originator
type VisionPersonImpl struct {
	DeletedAtValue    *UtcMs                       `json:"deleted_at,omitempty" validate:"omitempty,min=1e+12,max=1e+13"`
	ExternalIDValue   *string                      `json:"external_id,omitempty" validate:"omitempty"`
	OriginatorValue   VisionPersonOriginator       `json:"originator" validate:"required,oneof=api identification_service"`
	FingerprintsValue []*VisionFaceFingerprintImpl `json:"fingerprints,omitempty" validate:"omitempty"`
	PersonIDValue     SnowflakeID                  `json:"person_id" validate:"required"`
	UpdatedAtValue    UtcMs                        `json:"updated_at" validate:"required,min=1e+12,max=1e+13"`
}

// Person matching information
// Required: person, match_score
type VisionPersonMatchImpl struct {
	PersonValue     *VisionPersonImpl `json:"person" validate:"required"`
	MatchScoreValue float64           `json:"match_score" validate:"required"`
}

// Person matching information
type VisionPersonMatchesImpl struct {
	MatchedPersonsValue []*VisionPersonMatchImpl `json:"matched_persons,omitempty" validate:"omitempty"`
}

type VisionPersonsListImpl struct {
	TimingValue         any                 `json:"timing,omitempty" validate:"omitempty"`
	EstimatedCountValue *int                `json:"estimated_count,omitempty" validate:"omitempty"`
	NextValue           *string             `json:"next,omitempty" validate:"omitempty"`
	PrevValue           *string             `json:"prev,omitempty" validate:"omitempty"`
	PersonsValue        []*VisionPersonImpl `json:"persons" validate:"required"`
}

type VisionServerInfoImpl struct {
	BuildValue         *int           `json:"build,omitempty" validate:"omitempty"`
	NowValue           *UtcMs         `json:"now,omitempty" validate:"omitempty,min=1e+12,max=1e+13"`
	SchemaVersionValue *string        `json:"schema_version,omitempty" validate:"omitempty"`
	ServerVersionValue *ServerVersion `json:"server_version,omitempty" validate:"omitempty"`
	StartedAtValue     *Utc           `json:"started_at,omitempty" validate:"omitempty,min=1e+09,max=1e+10"`
}

// NewCollectionResponse creates a new CollectionResponse instance
func NewCollectionResponse() CollectionResponse {
	return &CollectionResponseImpl{}
}

// Estimated total number of records for the query (regardless of the cursors).
// Example: 5
func (s CollectionResponseImpl) EstimatedCount() *int {
	return s.EstimatedCountValue
}

// Estimated total number of records for the query (regardless of the cursors).
// Example: 5
func (s *CollectionResponseImpl) SetEstimatedCount(v int) CollectionResponse {
	if s == nil {
		return nil
	}
	s.EstimatedCountValue = &v
	return s
}

// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fZ3Q9MA==
func (s CollectionResponseImpl) Next() *string {
	return s.NextValue
}

// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fZ3Q9MA==
func (s *CollectionResponseImpl) SetNext(v string) CollectionResponse {
	if s == nil {
		return nil
	}
	s.NextValue = &v
	return s
}

// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
func (s CollectionResponseImpl) Prev() *string {
	return s.PrevValue
}

// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
func (s *CollectionResponseImpl) SetPrev(v string) CollectionResponse {
	if s == nil {
		return nil
	}
	s.PrevValue = &v
	return s
}

// An object with a list of different timings measured during this API call.
func (s CollectionResponseImpl) Timing() any {
	return s.TimingValue
}

// An object with a list of different timings measured during this API call.
func (s *CollectionResponseImpl) SetTiming(v any) CollectionResponse {
	if s == nil {
		return nil
	}
	s.TimingValue = v
	return s
}

// NewEpisodeFingerprint creates a new EpisodeFingerprint instance
func NewEpisodeFingerprint() EpisodeFingerprint {
	return &EpisodeFingerprintImpl{}
}

// Identifier of the episode that contains fingerprint to be identified
func (s EpisodeFingerprintImpl) EpisodeID() *int {
	return s.EpisodeIDValue
}

// Identifier of the episode that contains fingerprint to be identified
func (s *EpisodeFingerprintImpl) SetEpisodeID(v int) EpisodeFingerprint {
	if s == nil {
		return nil
	}
	s.EpisodeIDValue = &v
	return s
}

// Fingerprint to be identified
func (s EpisodeFingerprintImpl) Fingerprint() VisionFaceFingerprint {
	return s.FingerprintValue
}

// Fingerprint to be identified
func (s *EpisodeFingerprintImpl) SetFingerprint(v VisionFaceFingerprint) EpisodeFingerprint {
	if s == nil {
		return nil
	}
	if impl, ok := v.(*VisionFaceFingerprintImpl); ok {
		s.FingerprintValue = impl
	}
	return s
}

// NewEpisodeIdentificationError creates a new EpisodeIdentificationError instance
func NewEpisodeIdentificationError() EpisodeIdentificationError {
	return &EpisodeIdentificationErrorImpl{}
}

func (s EpisodeIdentificationErrorImpl) Code() *EpisodeIdentificationErrorCode {
	return s.CodeValue
}

func (s *EpisodeIdentificationErrorImpl) SetCode(v EpisodeIdentificationErrorCode) EpisodeIdentificationError {
	if s == nil {
		return nil
	}
	s.CodeValue = &v
	return s
}

// NewEpisodeIdentificationRequest creates a new EpisodeIdentificationRequest instance
func NewEpisodeIdentificationRequest() EpisodeIdentificationRequest {
	return &EpisodeIdentificationRequestImpl{}
}

// Batch of episodes containing fingerprints to be identified
func (s EpisodeIdentificationRequestImpl) Episodes() []EpisodeFingerprint {
	if s.EpisodesValue == nil {
		return nil
	}
	result := make([]EpisodeFingerprint, len(s.EpisodesValue))
	for i, item := range s.EpisodesValue {
		result[i] = item
	}
	return result
}

// Batch of episodes containing fingerprints to be identified
func (s *EpisodeIdentificationRequestImpl) SetEpisodes(v []EpisodeFingerprint) EpisodeIdentificationRequest {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*EpisodeFingerprintImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*EpisodeFingerprintImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.EpisodesValue = impl
	}
	return s
}

// NewError creates a new Error instance
func NewError() Error {
	return &ErrorImpl{}
}

// an application-specific error code, expressed as a string value
func (s ErrorImpl) Code() *string {
	return s.CodeValue
}

// an application-specific error code, expressed as a string value
func (s *ErrorImpl) SetCode(v string) Error {
	if s == nil {
		return nil
	}
	s.CodeValue = &v
	return s
}

// a unique identifier for this particular occurrence of the problem
func (s ErrorImpl) ID() *string {
	return s.IDValue
}

// a unique identifier for this particular occurrence of the problem
func (s *ErrorImpl) SetID(v string) Error {
	if s == nil {
		return nil
	}
	s.IDValue = &v
	return s
}

// a meta object containing non-standard meta-information about the error.
func (s ErrorImpl) Meta() map[string]string {
	return s.MetaValue
}

// a meta object containing non-standard meta-information about the error.
func (s *ErrorImpl) SetMeta(v map[string]string) Error {
	if s == nil {
		return nil
	}
	s.MetaValue = v
	return s
}

// an object containing references to the source of the error
func (s ErrorImpl) Source() ErrorSource {
	return s.SourceValue
}

// an object containing references to the source of the error
func (s *ErrorImpl) SetSource(v ErrorSource) Error {
	if s == nil {
		return nil
	}
	if impl, ok := v.(*ErrorSourceImpl); ok {
		s.SourceValue = impl
	}
	return s
}

// the HTTP status code applicable to this problem, expressed as a string value
func (s ErrorImpl) Status() *string {
	return s.StatusValue
}

// the HTTP status code applicable to this problem, expressed as a string value
func (s *ErrorImpl) SetStatus(v string) Error {
	if s == nil {
		return nil
	}
	s.StatusValue = &v
	return s
}

// a short, human-readable summary of the problem that SHOULD NOT change from
// occurrence to occurrence of the problem, except for purposes of localization
func (s ErrorImpl) Title() *string {
	return s.TitleValue
}

// a short, human-readable summary of the problem that SHOULD NOT change from
// occurrence to occurrence of the problem, except for purposes of localization
func (s *ErrorImpl) SetTitle(v string) Error {
	if s == nil {
		return nil
	}
	s.TitleValue = &v
	return s
}

// NewErrorResponse creates a new ErrorResponse instance
func NewErrorResponse() ErrorResponse {
	return &ErrorResponseImpl{}
}

// List of structured errors
func (s ErrorResponseImpl) Errors() []Error {
	if s.ErrorsValue == nil {
		return nil
	}
	result := make([]Error, len(s.ErrorsValue))
	for i, item := range s.ErrorsValue {
		result[i] = item
	}
	return result
}

// List of structured errors
func (s *ErrorResponseImpl) SetErrors(v []Error) ErrorResponse {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*ErrorImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*ErrorImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.ErrorsValue = impl
	}
	return s
}

// NewErrorSource creates a new ErrorSource instance
func NewErrorSource() ErrorSource {
	return &ErrorSourceImpl{}
}

// a string indicating which URI query parameter caused the error.
func (s ErrorSourceImpl) Parameter() *string {
	return s.ParameterValue
}

// a string indicating which URI query parameter caused the error.
func (s *ErrorSourceImpl) SetParameter(v string) ErrorSource {
	if s == nil {
		return nil
	}
	s.ParameterValue = &v
	return s
}

// a JSON Pointer [RFC6901] to the associated entity in the request document
// [e.g. `"/data"` for a primary data object, or `"/data/attributes/title"` for a specific attribute].
func (s ErrorSourceImpl) Pointer() *string {
	return s.PointerValue
}

// a JSON Pointer [RFC6901] to the associated entity in the request document
// [e.g. `"/data"` for a primary data object, or `"/data/attributes/title"` for a specific attribute].
func (s *ErrorSourceImpl) SetPointer(v string) ErrorSource {
	if s == nil {
		return nil
	}
	s.PointerValue = &v
	return s
}

// NewIdentificationMetrics creates a new IdentificationMetrics instance
func NewIdentificationMetrics() IdentificationMetrics {
	return &IdentificationMetricsImpl{}
}

// The number of identified episodes
func (s IdentificationMetricsImpl) EpisodesIdentifiedCount() *int {
	return s.EpisodesIdentifiedCountValue
}

// The number of identified episodes
func (s *IdentificationMetricsImpl) SetEpisodesIdentifiedCount(v int) IdentificationMetrics {
	if s == nil {
		return nil
	}
	s.EpisodesIdentifiedCountValue = &v
	return s
}

// The number of received episodes to identificate
func (s IdentificationMetricsImpl) EpisodesInputCount() *int {
	return s.EpisodesInputCountValue
}

// The number of received episodes to identificate
func (s *IdentificationMetricsImpl) SetEpisodesInputCount(v int) IdentificationMetrics {
	if s == nil {
		return nil
	}
	s.EpisodesInputCountValue = &v
	return s
}

// Total time spent on episode identification
// Format: milliseconds (milliseconds)
func (s IdentificationMetricsImpl) EpisodesProcessingTime() *Milliseconds {
	return s.EpisodesProcessingTimeValue
}

// Total time spent on episode identification
// Format: milliseconds (milliseconds)
func (s *IdentificationMetricsImpl) SetEpisodesProcessingTime(v Milliseconds) IdentificationMetrics {
	if s == nil {
		return nil
	}
	s.EpisodesProcessingTimeValue = &v
	return s
}

// The number of created persons
func (s IdentificationMetricsImpl) PersonsCreatedCount() *int {
	return s.PersonsCreatedCountValue
}

// The number of created persons
func (s *IdentificationMetricsImpl) SetPersonsCreatedCount(v int) IdentificationMetrics {
	if s == nil {
		return nil
	}
	s.PersonsCreatedCountValue = &v
	return s
}

// NewIdentifiedEpisode creates a new IdentifiedEpisode instance
func NewIdentifiedEpisode() IdentifiedEpisode {
	return &IdentifiedEpisodeImpl{}
}

// Identifier of the episode that contains fingerprint to be identified
func (s IdentifiedEpisodeImpl) EpisodeID() *int {
	return s.EpisodeIDValue
}

// Identifier of the episode that contains fingerprint to be identified
func (s *IdentifiedEpisodeImpl) SetEpisodeID(v int) IdentifiedEpisode {
	if s == nil {
		return nil
	}
	s.EpisodeIDValue = &v
	return s
}

func (s IdentifiedEpisodeImpl) IdentificationError() IdentifiedEpisodeIdentificationError {
	return s.IdentificationErrorValue
}

func (s *IdentifiedEpisodeImpl) SetIdentificationError(v IdentifiedEpisodeIdentificationError) IdentifiedEpisode {
	if s == nil {
		return nil
	}
	if impl, ok := v.(*IdentifiedEpisodeIdentificationErrorImpl); ok {
		s.IdentificationErrorValue = impl
	}
	return s
}

// List of matched persons with similarity metric
func (s IdentifiedEpisodeImpl) MatchedPersons() []VisionPersonMatch {
	if s.MatchedPersonsValue == nil {
		return nil
	}
	result := make([]VisionPersonMatch, len(s.MatchedPersonsValue))
	for i, item := range s.MatchedPersonsValue {
		result[i] = item
	}
	return result
}

// List of matched persons with similarity metric
func (s *IdentifiedEpisodeImpl) SetMatchedPersons(v []VisionPersonMatch) IdentifiedEpisode {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*VisionPersonMatchImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*VisionPersonMatchImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.MatchedPersonsValue = impl
	}
	return s
}

// NewIdentifiedEpisodeIdentificationError creates a new IdentifiedEpisodeIdentificationError instance
func NewIdentifiedEpisodeIdentificationError() IdentifiedEpisodeIdentificationError {
	return &IdentifiedEpisodeIdentificationErrorImpl{}
}

func (s IdentifiedEpisodeIdentificationErrorImpl) Code() *EpisodeIdentificationErrorCode {
	return s.CodeValue
}

func (s *IdentifiedEpisodeIdentificationErrorImpl) SetCode(v EpisodeIdentificationErrorCode) IdentifiedEpisodeIdentificationError {
	if s == nil {
		return nil
	}
	s.CodeValue = &v
	return s
}

// NewIdentifiedEpisodesList creates a new IdentifiedEpisodesList instance
func NewIdentifiedEpisodesList() IdentifiedEpisodesList {
	return &IdentifiedEpisodesListImpl{}
}

// Batch of identified fingerprints
func (s IdentifiedEpisodesListImpl) Episodes() []IdentifiedEpisode {
	if s.EpisodesValue == nil {
		return nil
	}
	result := make([]IdentifiedEpisode, len(s.EpisodesValue))
	for i, item := range s.EpisodesValue {
		result[i] = item
	}
	return result
}

// Batch of identified fingerprints
func (s *IdentifiedEpisodesListImpl) SetEpisodes(v []IdentifiedEpisode) IdentifiedEpisodesList {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*IdentifiedEpisodeImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*IdentifiedEpisodeImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.EpisodesValue = impl
	}
	return s
}

// NewVisionFaceFingerprint creates a new VisionFaceFingerprint instance
func NewVisionFaceFingerprint() VisionFaceFingerprint {
	return &VisionFaceFingerprintImpl{}
}

// Base64 encoded representation of the fingerprint
// Format: base64 (base64)
func (s VisionFaceFingerprintImpl) Data() Base64 {
	return s.DataValue
}

// Base64 encoded representation of the fingerprint
// Format: base64 (base64)
func (s *VisionFaceFingerprintImpl) SetData(v Base64) VisionFaceFingerprint {
	if s == nil {
		return nil
	}
	s.DataValue = v
	return s
}

// Version identifier of the fingerprint's data. The version is assigned automatically.
// Fingerprints of different versions cannot be compared to each other.
// Examples: aabbccdd, c6ba4246
func (s VisionFaceFingerprintImpl) Version() string {
	return s.VersionValue
}

// Version identifier of the fingerprint's data. The version is assigned automatically.
// Fingerprints of different versions cannot be compared to each other.
// Examples: aabbccdd, c6ba4246
func (s *VisionFaceFingerprintImpl) SetVersion(v string) VisionFaceFingerprint {
	if s == nil {
		return nil
	}
	s.VersionValue = v
	return s
}

// NewVisionPerson creates a new VisionPerson instance
func NewVisionPerson() VisionPerson {
	return &VisionPersonImpl{}
}

// When this person was marked as deleted
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.637095014573e+12
func (s VisionPersonImpl) DeletedAt() *UtcMs {
	return s.DeletedAtValue
}

// When this person was marked as deleted
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.637095014573e+12
func (s *VisionPersonImpl) SetDeletedAt(v UtcMs) VisionPerson {
	if s == nil {
		return nil
	}
	s.DeletedAtValue = &v
	return s
}

// Identifier of the person in the external system.
// Use it when supplying the recognition results further into the external system
// (e.g. for access level check) if the person identifiers in the external system
// are different from the ones in Flussonic Identification database.
// This field may contain `null` when video analytics detects a new person
// which explicitly has no association in the external system (i.e. if `originator=identification_service`).
// Examples: dedcc8e8
func (s VisionPersonImpl) ExternalID() *string {
	return s.ExternalIDValue
}

// Identifier of the person in the external system.
// Use it when supplying the recognition results further into the external system
// (e.g. for access level check) if the person identifiers in the external system
// are different from the ones in Flussonic Identification database.
// This field may contain `null` when video analytics detects a new person
// which explicitly has no association in the external system (i.e. if `originator=identification_service`).
// Examples: dedcc8e8
func (s *VisionPersonImpl) SetExternalID(v string) VisionPerson {
	if s == nil {
		return nil
	}
	s.ExternalIDValue = &v
	return s
}

// Digital fingerprints of the person.
// Videoanalytics makes digital fingerprint of the person
// using uploaded photos or videostreams being processed
func (s VisionPersonImpl) Fingerprints() []VisionFaceFingerprint {
	if s.FingerprintsValue == nil {
		return nil
	}
	result := make([]VisionFaceFingerprint, len(s.FingerprintsValue))
	for i, item := range s.FingerprintsValue {
		result[i] = item
	}
	return result
}

// Digital fingerprints of the person.
// Videoanalytics makes digital fingerprint of the person
// using uploaded photos or videostreams being processed
func (s *VisionPersonImpl) SetFingerprints(v []VisionFaceFingerprint) VisionPerson {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*VisionFaceFingerprintImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*VisionFaceFingerprintImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.FingerprintsValue = impl
	}
	return s
}

// Indicates the way this person was created:
// manually via an api or automatically in the identification service.
func (s VisionPersonImpl) Originator() VisionPersonOriginator {
	return s.OriginatorValue
}

// Indicates the way this person was created:
// manually via an api or automatically in the identification service.
func (s *VisionPersonImpl) SetOriginator(v VisionPersonOriginator) VisionPerson {
	if s == nil {
		return nil
	}
	s.OriginatorValue = v
	return s
}

// Identifier of the person
// Format: snowflake_id (snowflake_id)
// Examples: 7.036001172460667e+18
func (s VisionPersonImpl) PersonID() SnowflakeID {
	return s.PersonIDValue
}

// Identifier of the person
// Format: snowflake_id (snowflake_id)
// Examples: 7.036001172460667e+18
func (s *VisionPersonImpl) SetPersonID(v SnowflakeID) VisionPerson {
	if s == nil {
		return nil
	}
	s.PersonIDValue = v
	return s
}

// When this person was last updated
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.637034282845e+12
func (s VisionPersonImpl) UpdatedAt() UtcMs {
	return s.UpdatedAtValue
}

// When this person was last updated
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.637034282845e+12
func (s *VisionPersonImpl) SetUpdatedAt(v UtcMs) VisionPerson {
	if s == nil {
		return nil
	}
	s.UpdatedAtValue = v
	return s
}

// NewVisionPersonMatch creates a new VisionPersonMatch instance
func NewVisionPersonMatch() VisionPersonMatch {
	return &VisionPersonMatchImpl{}
}

// Score of the match with person. 1.0 means absolute match
func (s VisionPersonMatchImpl) MatchScore() float64 {
	return s.MatchScoreValue
}

// Score of the match with person. 1.0 means absolute match
func (s *VisionPersonMatchImpl) SetMatchScore(v float64) VisionPersonMatch {
	if s == nil {
		return nil
	}
	s.MatchScoreValue = v
	return s
}

// Matched person
func (s VisionPersonMatchImpl) Person() VisionPerson {
	return s.PersonValue
}

// Matched person
func (s *VisionPersonMatchImpl) SetPerson(v VisionPerson) VisionPersonMatch {
	if s == nil {
		return nil
	}
	if impl, ok := v.(*VisionPersonImpl); ok {
		s.PersonValue = impl
	}
	return s
}

// NewVisionPersonMatches creates a new VisionPersonMatches instance
func NewVisionPersonMatches() VisionPersonMatches {
	return &VisionPersonMatchesImpl{}
}

// List of matched persons with similarity metric
func (s VisionPersonMatchesImpl) MatchedPersons() []VisionPersonMatch {
	if s.MatchedPersonsValue == nil {
		return nil
	}
	result := make([]VisionPersonMatch, len(s.MatchedPersonsValue))
	for i, item := range s.MatchedPersonsValue {
		result[i] = item
	}
	return result
}

// List of matched persons with similarity metric
func (s *VisionPersonMatchesImpl) SetMatchedPersons(v []VisionPersonMatch) VisionPersonMatches {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*VisionPersonMatchImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*VisionPersonMatchImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.MatchedPersonsValue = impl
	}
	return s
}

// NewVisionPersonsList creates a new VisionPersonsList instance
func NewVisionPersonsList() VisionPersonsList {
	return &VisionPersonsListImpl{}
}

// Estimated total number of records for the query (regardless of the cursors).
// Example: 5
func (s VisionPersonsListImpl) EstimatedCount() *int {
	return s.EstimatedCountValue
}

// Estimated total number of records for the query (regardless of the cursors).
// Example: 5
func (s *VisionPersonsListImpl) SetEstimatedCount(v int) VisionPersonsList {
	if s == nil {
		return nil
	}
	s.EstimatedCountValue = &v
	return s
}

// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fZ3Q9MA==
func (s VisionPersonsListImpl) Next() *string {
	return s.NextValue
}

// Next cursor: a properly encoded equivalent of offset allowing to read the next bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fZ3Q9MA==
func (s *VisionPersonsListImpl) SetNext(v string) VisionPersonsList {
	if s == nil {
		return nil
	}
	s.NextValue = &v
	return s
}

// List of fetched persons according to the query parameters.
func (s VisionPersonsListImpl) Persons() []VisionPerson {
	if s.PersonsValue == nil {
		return nil
	}
	result := make([]VisionPerson, len(s.PersonsValue))
	for i, item := range s.PersonsValue {
		result[i] = item
	}
	return result
}

// List of fetched persons according to the query parameters.
func (s *VisionPersonsListImpl) SetPersons(v []VisionPerson) VisionPersonsList {
	if s == nil {
		return nil
	}
	if v != nil {
		impl := make([]*VisionPersonImpl, len(v))
		for i, item := range v {
			if itemImpl, ok := item.(*VisionPersonImpl); ok {
				impl[i] = itemImpl
			}
		}
		s.PersonsValue = impl
	}
	return s
}

// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
func (s VisionPersonsListImpl) Prev() *string {
	return s.PrevValue
}

// Previous cursor: a properly encoded equivalent of offset allowing to read the previous bunch of items.
// Learn more in [Flussonic API design principles](https://flussonic.com/doc/rest-api-guidelines/#api-http-collections-cursor).
// Example: JTI0cG9zaXRpb25fbHQ9MSYlMjRyZXZlcnNlZD10cnVl
func (s *VisionPersonsListImpl) SetPrev(v string) VisionPersonsList {
	if s == nil {
		return nil
	}
	s.PrevValue = &v
	return s
}

// An object with a list of different timings measured during this API call.
func (s VisionPersonsListImpl) Timing() any {
	return s.TimingValue
}

// An object with a list of different timings measured during this API call.
func (s *VisionPersonsListImpl) SetTiming(v any) VisionPersonsList {
	if s == nil {
		return nil
	}
	s.TimingValue = v
	return s
}

// Collection returns the collection items from VisionPersonsList
func (s VisionPersonsListImpl) Collection() []VisionPerson {
	return s.Persons()
}

// NewVisionServerInfo creates a new VisionServerInfo instance
func NewVisionServerInfo() VisionServerInfo {
	return &VisionServerInfoImpl{}
}

// Build version
// Example: 235
func (s VisionServerInfoImpl) Build() *int {
	return s.BuildValue
}

// Build version
// Example: 235
func (s *VisionServerInfoImpl) SetBuild(v int) VisionServerInfo {
	if s == nil {
		return nil
	}
	s.BuildValue = &v
	return s
}

// Server's current timestamp
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.639337825e+12
func (s VisionServerInfoImpl) Now() *UtcMs {
	return s.NowValue
}

// Server's current timestamp
// Format: utc_ms (Unix timestamp in milliseconds)
// Example: 1.639337825e+12
func (s *VisionServerInfoImpl) SetNow(v UtcMs) VisionServerInfo {
	if s == nil {
		return nil
	}
	s.NowValue = &v
	return s
}

// API schema revision implemented in this version of the server
// Example: 5e5e91d8
func (s VisionServerInfoImpl) SchemaVersion() *string {
	return s.SchemaVersionValue
}

// API schema revision implemented in this version of the server
// Example: 5e5e91d8
func (s *VisionServerInfoImpl) SetSchemaVersion(v string) VisionServerInfo {
	if s == nil {
		return nil
	}
	s.SchemaVersionValue = &v
	return s
}

// Package version of the server. Might be simple a number of release like 21.11 or longer if you have a rolling release installed.
// Format: server_version (server_version)
// Example: 21.12
func (s VisionServerInfoImpl) ServerVersion() *ServerVersion {
	return s.ServerVersionValue
}

// Package version of the server. Might be simple a number of release like 21.11 or longer if you have a rolling release installed.
// Format: server_version (server_version)
// Example: 21.12
func (s *VisionServerInfoImpl) SetServerVersion(v ServerVersion) VisionServerInfo {
	if s == nil {
		return nil
	}
	s.ServerVersionValue = &v
	return s
}

// Timestamp when this instance was started
// Format: utc (Unix timestamp in seconds)
// Example: 1.639337825e+09
func (s VisionServerInfoImpl) StartedAt() *Utc {
	return s.StartedAtValue
}

// Timestamp when this instance was started
// Format: utc (Unix timestamp in seconds)
// Example: 1.639337825e+09
func (s *VisionServerInfoImpl) SetStartedAt(v Utc) VisionServerInfo {
	if s == nil {
		return nil
	}
	s.StartedAtValue = &v
	return s
}
