# Global settings:
http 80;
rtsp 554;

event_sink central_event_collector {
  url http://central/central/api/v3/events/collector;
  only event=stream_motion_started,stream_motion_stopped,motion_started,motion_stopped;
}

auth_backend vsaas {
  backend http://central/central/api/v3/auth;
}

# DVRs:
dvr watcher {
  root /storage;
}

vod vod {
  storage /vod_storage;
}

# Components:
rproxy {
  forward_port 5025 camera_alarm_rproxy;
  streampoint_key ZSSlAAAAAGYELu0DoA==;
}
